services:
  db:
    image: postgres:16-alpine
    container_name: ai_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-ai_analisis_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-ai_analisis_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ai_network

  api:
    build: .
    container_name: ai_fastapi_app
    restart: always
    # 1. Agregamos  para que FastAPI detecte cambios en los archivos
    command: >
      sh -c "python sync_models.py && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000 "
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@db:5432/${POSTGRES_DB:-ai_analisis_db}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    env_file:
      - .env
    # 2. MAPEAMOS TU CARPETA LOCAL CON LA DEL CONTENEDOR
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge

volumes:
  postgres_data: